title: Sílvio Meireles Blog
description: "My Personal Blog"
author:
  name: "Sílvio Meireles"
  email: "contato@silviomeireles.dev"
  url: "mastersilvio.github.io"
  baseurl: /mastersilvio.github.io

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-pwa-plugin

# Custom variables
owner : "silviomeireles"
year : "2019"
google_analytics: UA-147349907-1

pwa:
  sw_src_filepath: service-worker.js # Optional
  sw_dest_filename: service-worker.js # Optional
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
    - index.html
  precache_glob_ignores: # Optional
    - sw-register.js
    - "fonts/**/*"
