title: Sílvio Meireles Blog
description: "My Personal Blog"
author:
  name: "Sílvio Meireles"
  email: "contato@silviomeireles.dev"
  url: "mastersilvio.github.io"
  baseurl: /mastersilvio.github.io

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "silviomeireles"
year : "2019"
google_analytics: UA-147349907-1

name: "Sílvio Meireles Blog"
short_name: "SM Blog"
url: "https://silviomeireles.dev"
language: "pt-BR"
lang_direction: "ltr"
color: "#151515"
