services:
  site:
    build: .
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle
    ports:
      - "4000:4000"
    environment:
      - JEKYLL_ENV=development
      - BUNDLE_PATH=/usr/local/bundle
      - GEM_HOME=/usr/local/bundle
    tty: true
    stdin_open: true

volumes:
  gem_cache:

